// coloniasMacros.js - Lista de colonias y macros para el dropdown con filtrado

export const COLONIAS_MACROS = [
    "CENTRO", "SAN JUAN DE DIOS", "LUZ MARIA DIAZ INFANTE", "SAN MIGUEL", "LA MARTINICA",
    "ANDRADE", "LEON MODERNO", "LAS ARBOLEDAS", "EL PAISAJE", "SAN NICOLAS",
    "MIGUEL HIDALGO", "PRADOS VERDES", "SAN MIGUEL INFONAVIT", "LA FLORESTA", "SANTA CLARA",
    "LA ESCONDIDA", "LOURDES", "SAN JOSE DE CEMENTOS", "PASEOS DEL MAUREL", "LAS AMERICAS",
    "INDEPENDENCIA", "GUADALUPE", "LOS FRESNOS", "SAN SEBASTIAN", "JARDINES DE SAN SEBASTIAN",
    "PLAZA DE TOROS I", "LAS MARGARITAS", "LOS AGUACATES", "VALLE DEL SUR", "LA LUZ",
    "SAN RAFAEL", "SANTA RITA", "FRANCISCO LOZORNIO", "TEPEYAC", "ACROPOLIS",
    "FRACCION DE SAN NICOLAS", "RIO ESCONDIDO", "VILLANUEVA", "PLAZA DE TOROS II",
    "JARDINES DE SAN SEBASTIAN II", "JARDINES DE SAN MIGUEL", "RIBERA DEL RIO", "BUENOS AIRES",
    "SAN IGNACIO", "VALLE DE ALBORADA", "ZONA RECREATIVA Y CULTURAL", "INDUSTRIAL JUAREZ",
    "CONJUNTO SAN LUIS", "FRACCION DEL COECILLO", "EL TLACUACHE", "PLAZA DE TOROS III",
    "OBRERA", "BELLAVISTA", "LOMA BONITA", "CUMBRES DE ARBIDE", "BUENA VISTA",
    "LOS LIMONES", "LOMAS DE LA PISCINA", "SANTA RITA DE LOS NARANJOS", "LA PISCINA CTM",
    "LOS LAURELES", "LAS MANDARINAS (I Y II)", "CIUDAD SATELITE (LA HERRADURA)", "SAN MARCOS",
    "FLORES MAGON E.", "SAN MARTIN DE PORRES", "VISTA HERMOSA (SUR)", "CHAPALITA",
    "ARBIDE", "LAS PALMAS", "JHON F. KENNEDY", "LOS OLIVOS", "GRANJAS CAMPESTRE",
    "LA PISCINA (KM 3.5)", "LAS HUERTAS", "GRANJAS LAS AMALIAS", "PORTALES DE SAN SEBASTIAN",
    "MORELOS (EL GUAJE)", "SANTA CROCCE INDUSTRIAL", "VILLA RESIDENCIAL ARBIDE",
    "LA MERCED (RAMIREZ GARCIA)", "LADERA DE JEREZ", "CHULA VISTA", "MIRADOR DE ARBIDE",
    "LOMAS DE ARBIDE", "LOMAS DE LOS OLIVOS", "MONTE DE CRISTO I Y II",
    "MIGUEL DE CERVANTES SAAVEDRA", "RINCON DE LOS OLIVOS", "EL SALTO",
    "CLUB CINEGETICO LEONES", "COLINAS DE LEON", "LEON II", "VILLA DEL PALMAR",
    "JOL-GUA-BER", "SAN CRISPIN", "COMPLEJO LA CIMA", "DEL COSMOS", "CIUDAD SATELITE III",
    "SANTA CROCCE II", "VIBAR", "LAS HILAMAS INFONAVIT", "LOMA REAL",
    "DEPORTIVA J. J. RODRIGUEZ", "INDUSTRIAL PAMPLONA", "INDUSTRIAL SAN JORGE",
    "LOMAS DEL CONDADO", "HACIENDA LAS MANDARINAS", "PALMAS 2000", "LAS HILAMAS III SECCION",
    "VALLE DE ARBIDE", "CENTRO BODEGUERO ROBLES", "LOMAS DEL VALLE", "CUMBRES DE LA PISCINA",
    "VALLE DEL ROCIO", "LA CUMBRE", "BETANIA", "CAMPO VERDE", "LA LUCITA",
    "PERIODISTAS MEXICANOS", "BALCONES DE LA JOYA", "CENTRO FAMILIAR LA PIEDAD",
    "CENTRO FAMILIAR SOLEDAD", "PASEOS DE LA JOYA", "JOYAS DE LA LOMA", "LA JOYA (EJIDO)",
    "COLINAS DE LA HACIENDA", "SAUCILLO DE LA JOYA", "VILLAS DE LA JOYA", "REAL DE LA JOYA",
    "RIZOS DEL SAUCILLO 1RA. Y 2DA", "ERMITA  1RA. Y 2DA. SECC", "JARDINES DEL MORAL",
    "LOS PARAISOS", "MODERNA", "SAN ANTONIO", "INDUSTRIAL (HAB.)", "ESPAÑA",
    "SAN JUAN BOSCO (VISTA HERMOSA)", "EL MIRADOR (CAMPESTRE)", "PILETAS", "LINDA VISTA",
    "LOMAS DEL SOL", "LOMAS DE LA TRINIDAD", "GRANADA", "LOMAS DEL CAMPESTRE SEC VILLAS",
    "PANORAMA", "VALLE DEL CAMPESTRE", "CLUB CAMPESTRE", "FUTURAMA MONTERREY",
    "VILLAS DEL MORAL", "LA FLORIDA(RANCHO)", "SAN JOSE OBRERO", "RESIDENCIAL DEL MORAL I",
    "PRIV. DEL MORAL", "EL REFUGIO CAMPESTRE", "RESIDENCIAL DEL MORAL II", "PILETAS III",
    "PORTONES DEL CAMPESTRE", "VILLAS DEL CAMPESTRE", "CUMBRES DEL CAMPESTRE",
    "RINCON DEL CAMPESTRE", "BOSQUES DEL REFUGIO", "LOMAS DE VISTA HERMOSA", "PILETAS IV",
    "GASOLINERA DE LA Y A LAGOS", "BOSQUES DEL CAMPESTRE", "BALCONES DEL CAMPESTRE",
    "DESARROLLO BALEARES", "PLAZA MAYOR", "LAS QUINTAS", "JARDINES DEL CAMPESTRE",
    "REAL CAMPESTRE", "LAGOS DEL CAMPESTRE", "EL COECILLO", "KILLIAN I", "KILLIAN II",
    "LOS GAVILANES", "OBREGON", "BARRIO DE SANTIAGO", "EL DURAZNAL", "PEÑITAS",
    "LA MARGARITA", "CASA BLANCA", "HEROES DE CHAPULTEPEC", "LA FLORIDA",
    "RINCON DE LA FLORIDA", "MICHOACAN", "LA BRISA", "SAN AGUSTIN", "EL RETIRO",
    "HIDALGO", "INSURGENTES", "INDEPENDENCIA INFONAVIT", "POPULAR ANAYA", "LAS TROJES",
    "EL CORTIJO", "LA CARMONA", "PROVIDENCIA", "PRESIDENTES DE MEXICO", "SAN MANUEL",
    "LA CANDELARIA", "NUEVA CANDELARIA", "LINARES", "BENITO JUAREZ", "UNIDAD DEPORTIVA I",
    "LOS PINITOS", "JOSEFINA", "ESPAÑITA", "ESTRELLA", "SANTA FE",
    "LA MORA (CRUZ DE CANTERA)", "PALOMARES", "SAN JERONIMO I SECCION", "REAL PROVIDENCIA I",
    "EL TRIANON", "SAN JERONIMO II SUR", "REAL PROVIDENCIA II", "PANTEON JARDINES DE LEON",
    "JARDINES DE PROVIDENCIA", "EL LUCERO", "C.H. VALTIERRA", "PORTONES DEL MORAL",
    "VILLA INSURGENTES", "JULIAN CARRILLO", "BOSQUES DEL VALLE",
    "PRIV. RINCONADA DE LAS FLORES", "LA ANTIQUA I", "UNIDAD DEPORTIVA COECILLO",
    "LOS TORONJALES", "VALLE DEL SOL", "VALLE DE LEON", "CIUDAD AURORA",
    "UNIDAD OBRERA (INFONAVIT)", "EL PALOTE", "SAN JERONIMO II SECC. (NORTE)", "LAS AGUILAS",
    "EL PELUCHAN (I)", "LOS CEDROS", "HACIENDAS EL ROSARIO", "LA HERRADURA",
    "GRANJAS EL PALOTE", "VILLAS DEL ROSARIO", "EL ROSARIO", "C.H. SAN CRISTOBAL",
    "REAL DEL BOSQUE I", "REAL DEL CASTILLO", "REAL DEL BOSQUE II", "LA HACIENDA",
    "REAL DE CAMELINAS", "TORRES DEL LAGO", "C.H. LA ESPERANZA", "VALLE DEL MORAL",
    "LA PLACITA", "HACIENDA DEL CAMPESTRE", "PRADERAS DE ECHEVESTE", "REAL DEL BOSQUE 1ra.",
    "RINCONADA DEL BOSQUE", "BOSQUES DE LA PRESA", "FINCAS SAAVEDRA", "JARDINES DE ECHEVESTE",
    "EL VIVERO VALLE DE LEON", "SAN JOSE DEL CONSUELO", "VALLE DE SEÑORA",
    "SANTA ROSA DE LIMA", "SAN JOSE DEL CONSUELO II SECC.", "UNIDAD DEPORTIVA II",
    "LOS NARANJOS", "SANTA ROSA DE LIMA II", "PALENQUE DE IBARRILLA", "SAN PABLO",
    "INDUSTRIAL DEL NORTE", "REAL DE SAN JOSE (CONSERVATORIO)",
    "CONJUNTO HABITACIONAL COECILLO", "VALLE DE SAN BERNARDO", "ARBOLEDA DE SEÑORA",
    "IBARRILLA POBLADO", "EL VALLADITO I Y II", "UNION COMUNITARIA DE LEON NTE",
    "ARBOLEDA DE IBARRILLA", "LAS PRESITAS", "LAS PRESITAS DEL CONSUELO",
    "LOMAS DE LAS PRESITAS", "LA SELVA", "LAURELES DE LA SELVA I", "LAURELES DE LA SELVA II",
    "LA SELVA II", "VILLA DE LA ROSA", "LOS PIRULES", "JARDINES DEL BOSQUE",
    "VALLE DE SEÑORA II SECC.", "HIDALGO DEL VALLE", "MISION DE SAN JOSE",
    "MISION DE LA FLORIDA", "REVOLUCION", "RESIDENCIAL VICTORIA", "MISION DEL NORTE",
    "SAN BENIGNO", "VILLAS VASCO DE QUIROGA", "TORRES DE STA ROSA,LAS(ALAMEDA)",
    "EL PENITENTE", "RESIDENCIAL EL CONDADO", "SAN NICOLAS DE LOS REYES",
    "SAN PEDRO DE LOS HERNANDEZ", "SAN JORGE", "PUNTO VERDE", "JARDINES DE SAN PEDRO",
    "INDUSTRIAL JULIAN DE OBREGON", "BARRIO DE GUADALUPE", "BUGAMBILIAS",
    "SAN FELIPE DE JESUS", "LOS ANGELES", "JARDINES DE ORIENTE", "GRANJAS CERES",
    "EYUPOL", "LEON I", "EL REFUGIO", "CONSTITUYENTES DE GUANAJUATO",
    "UNIDAD Y ESFUERZO POP (UYEPAC)", "LAS FUENTES", "LEON I AMPLIACION",
    "VILLA DE LAS FLORES", "SAN MIGUEL DE RENTERIA", "PRADO HERMOSO",
    "VILLA VERDE (TERRANOVA)", "SAN ANGEL CAMPESTRE", "LAS ROSAS", "POPULAR LA LUZ",
    "FLECHA AMARILLA", "SAN PEDRO PLUS", "CONJUNTO VERSALLES", "RINCONADA DE SAN PEDRO",
    "BOSQUES DE RENTERIA", "LOS PORTONES", "LAS GLORIAS", "MISION DE LA LUZ",
    "RESIDENCIAL REAL VICTORIA", "FRACCION DE JAR DE SAN PEDRITO", "PORTONES DE SAN PEDRITO",
    "PUEBLO NUEVO", "SAN MIGUEL RUSTICO", "TALLERES FLECHA AMARILLA", "BRISAS DEL CAMPO I",
    "BRISAS DEL CAMPO (LA CAPILLA)", "EL CARMEN RESIDENCIAL", "BRISAS DEL CAMPO II SECC.HAB",
    "EL CID", "LOMA VERDE", "CAÑADA DE ALFARO", "NUEVO AMANECER", "EL PEÑON",
    "SAN FRANCISCO I SECC.", "PEDREGAL DEL CARMEN", "LAS CRUCES", "SAN CARLOS RESIDENCIAL",
    "ANGELES Y MEDINA", "EL CARMEN (C.T.M.)", "MARAVILLAS I", "LOMAS DE MEDINA",
    "EJIDO MEDINA", "CRISTO REY (ANTES SN.FCO.A.C.)", "PARAISO REAL", "NUEVO SAN NICOLAS",
    "SANGRE DE CRISTO (S. FRACO.II)", "MARAVILLAS II", "MARAVILLAS III", "EL CARMEN",
    "ALFARO", "LA CAMPIÑA", "INDUSTRIAL LA CAPILLA", "HACIENDAS DE LEON", "MAGISTERIAL",
    "CERRITO DE JEREZ", "DELTA INDUSTRIAL", "LIBERTAD", "CAMPESTRE NUEVO JEREZ",
    "DIEZ DE MAYO", "LAS TORRES", "UNION OBRERA", "VALLE DE SAN JOSE", "VILLA DE LEON",
    "SAN JOSE EL ALTO", "BALCONES DE JEREZ", "VALLE DE JEREZ", "LOMAS DE JEREZ",
    "LA ESPERANZA (POP. ESPERANZA)", "POPULAR POLANCO", "ARBOLEDA DEL REFUGIO",
    "ARBOLEDA SAN HILARION", "CAMPESTRE DE JEREZ", "REFUGIO DE SAN JOSE",
    "POPULAR GUADALUPE", "REAL DE JEREZ", "MARIA DE LA LUZ", "DELTA DE JEREZ",
    "CAÑADA DE JEREZ", "LA GLORIA", "PEDREGAL DE JEREZ", "SAN JUAN BAUTISTA",
    "COLINAS DE JEREZ", "LA RAZA", "COLINAS DE SAN ISIDRO", "LOMA HERMOSA", "JARDIN DELTA",
    "VALLE DORADO", "EL MIRADOR ORIENTAL", "ORIENTAL", "PARQUE MANZANARES",
    "SAN ISIDRO DE JEREZ I Y II SEC", "JARDINES DE JEREZ II/III", "ORIENTAL ANAYA",
    "AZTECA", "SAN ISIDRO(SAN DIEGO)", "JARDINES DE JEREZ I SECC.", "EL GRANJENO",
    "RINCONADA DEL SUR", "MARIA DOLORES", "JESUS DE NAZARET", "SAN ISIDRO DE JEREZ I",
    "PARQUES DEL SUR II", "PARQUES DEL SUR III SECC", "JARDINES DE JEREZ III SECC.",
    "EL GRANJENO (IVEG)", "VILLAS SAN ISIDRO", "JARDINES DE LA PRADERA",
    "SANTA MARIA DE CEMENTOS", "LOS PINOS", "CIUDAD INDUSTRIAL (STA. LUCIA)",
    "CENTRAL DE ABASTOS", "PARQUE ECOLOGICO DE LEON", "ARBOLEDAS DEL CAMPO",
    "CAMPESTRE SAN JOSE", "LA LABORCITA", "ARBOLEDA LOS LOPEZ II", "MISION SANTA FE",
    "RESIDENCIAL CAMPESTRE SAN JOSE", "SAN JOSE DEL CLAVEL", "STA ROSA PLAN DE AYALA",
    "LA ESMERALDA", "LA VENTA", "RUSTICO SAN PEDRO", "PUERTA DEL CERRO",
    "CASTILLOS VIEJOS 1 SECC", "PORTONES DEL CARMEN", "PUERTA DEL CERRO",
    "ESPERANZA DE JEREZ", "VILLAS PRADERA", "ARROYO HONDO", "TORRES DEL ROSARIO",
    "COMUNIDAD MONTERREY", "POTRERO DEL CERRO", "BOSQUES", "JARDINES DE MARAVILLAS",
    "LOS CARCAMOS", "SAN CRISTOBAL", "SANTA JULIA", "PEDREGAL SAN CARLOS",
    "RESIDENCIAL CAMPESTRE SAN JOSE", "PARQUES Y JARDINES", "LINEA TURBIO", "LOS ARCOS",
    "SAN JOSE DEL CARMEN", "PUERTA SAN GERMAN", "FRACC. BOSQUES", "SANTA MARIA (LA ESTACION)",
    "PENSILVANIA", "SAN BERNARDO", "RANCHO LA MORA", "SAN ISIDRO", "SAN JOSE DE LOS TANQUES",
    "SAN JOSE DEL DURAN EL MAGURO", "RANCHO SAN CRISTOBAL", "EJIDO DE POMPA",
    "COLONIA POR CODIFICAR", "XOCONOSTLE", "SAN FRANCISCO DEL RINCON GTO",
    "PRIV.ECHEVESTE ANT.RANCH.ECHEV", "PURISIMA DE JEREZ", "BOSQUES DE LEON", "DELTA",
    "RESID.SAN JERONIMO IV ETAPA", "LA NORIA (CASTILLOS)", "EL CAPULIN(FRACCION CERRO G)",
    "SANTA CRUZ (NTE.DE ECHEVESTE)", "VILLA DE LAS TORRES", "PORTONES DE HIERRO",
    "RUSTICO LA ESMERALDA", "LATINOAMERICANA", "SANTO DOMINGO II", "DELTA 2000",
    "CARRETERA LEON-SN FELIPE", "VALLE DEL MAGUEY", "VILLAS DE SANTA JULIA",
    "SAN JOSE DE SANTA JULIA", "SAN JOSE DE LAS PILETAS", "FRACCION DE LOS GOMEZ NTE",
    "CONJUNTO BELEN", "INCA", "RESIDENTES CAMPESTRE", "VILLAS CERVANTES",
    "PORTALES DE LA ARBOLEDA", "JARDINES DE SANTA JULIA", "LA PECHUGA", "PUNTA CAMPESTRE",
    "CONVIVE", "LOMAS DEL MIRADOR", "PEDREGALES DE ECHEVESTE", "ALAMEDA DIAMANTE",
    "LEON II 3RA SECCION", "JESUS MARIA", "ARRAYANES", "AGUA AZUL", "CAÑADA DEL REFUGIO",
    "VALLE JACARANDAS", "VALLE DE SAN NICOLAS", "MEZQUITAL 2000",
    "PRIVADA MISION DE SAN JOSE", "PRADERAS DE SANTA ROSA", "RENACIMIENTO",
    "COLINAS DE SANTA JULIA", "SAN FRANCISCO (AMPLIACION)", "VILLAS BUGAMBILIAS",
    "ARBOLEDAS DE SAN PEDRO", "PASEOS DE MIRAVALLE", "VALLE DELTA", "ECHEVESTE 2000",
    "EL POCHOTE", "JARDINES DEL SOL", "VILLAS DE SAN JUAN I", "HACIENDA ECHEVESTE",
    "RIBERA DE LA PRESA COUNTRY", "LOMAS DE ECHEVESTE", "EL CASTILLO", "LA LAGUNITA",
    "NUEVO LEON", "PRIVADA ECHEVESTE", "SAN NICOLAS DEL PALOTE II", "VILLAS DE ECHEVESTE",
    "EL PARADOR", "SAN JAVIER", "RIVERA DE LA PRESA", "VALLE HERMOSO II,III,IV",
    "VALLE HERMOSO I Y V", "SANTA CECILIA I", "SANTA CECILIA II", "LA INDIA",
    "CAÑON DE LA INDIA", "TIRITAS I II", "EL POTRERO", "LOMAS DE GUADALUPE",
    "BALCONES TULIPANES", "RIVERA DE LOS CASTILLOS", "CANTERITAS DE ECHEVESTE",
    "POBLADO LOS CASTILLOS", "LA NORTEÑA", "SAN ISIDRO LABRADOR",
    "ARBOLEDAS DE LOS CASTILLOS I", "LOMAS DE LOS CASTILLOS", "LA PRADERA",
    "LOS CASTILLOS(ARB.LOS CASTILL)", "LOS CUARENTEÑOS", "ARBOLEDAS DE LOS CASTILLOS II",
    "POPULAR MAYA", "CASTILLOS VIEJOS", "PASO DEL RIO DE LOS CASTILLOS",
    "SAN JORGE DE LOS CASTILLOS", "VILLA MAGNA", "REAL DE BUGAMBILIAS",
    "VALLE DE LOS CASTILLOS", "COLINAS DE GRAN JARDIN", "VALLE DEL REAL",
    "VALLE DE LAS TORRES", "BOSQUES REALES", "PARQUE LA NORIA", "MEZQUITAL DE JEREZ",
    "VILLAS MARIANA", "VALLE DE LOS NARANJOS", "LOS MURALES", "ADQUIRIENTES DE IBARRILLA",
    "HACIENDA DE LOS NARANJOS", "VILLAS DEL JUNCAL", "PRIVADA LAS ROSAS",
    "SANTA MARIA DEL GRANJENO", "PARQUES DEL SUR I", "8 DE MARZO", "11 DE JUNIO",
    "C.H.ISLAS DE LEON", "LA MOREÑA", "JARDINES DE MARAVILLAS 2 SECC", "BOSQUES DEL SUR",
    "CASTILLOS SUR", "PARQUES DE LA PRADERA", "ARRAYANES 1RA. SECCION",
    "PRESITAS II SECCION", "RESIDENCIAL CAMELINAS", "LAS VILLAS", "SAN PEDRITO DE ECHEVESTE",
    "BRISAS DEL CARMEN", "VALLE DE LAS HACIENDAS(MONTE C)", "LOMAS DE LA PRESA",
    "REAL DE LOS NARANJOS", "BRISAS DE SAN NICOLAS", "VILLAS DE SANTA TERESITA",
    "QUINTA LOS CASTILLOS", "VILLAS VASCO DE QUIROGA", "EL CONSUELO(SAN PABLO)",
    "CERRO GORDO", "PASEOS DE LA CIMA", "OBSERVATORIO", "RESIDENCIAL LAS QUINTAS",
    "LA HUERTA", "MANANTIALES", "QUINTAS SAN LORENZO", "ANTENAS DE ARRIBA",
    "AMPLIACION MESITAS DEL CONSUEL", "LOMAS DE GRAN JARDIN", "REAL DE LEON", "REAL DELTA",
    "CHICHIHUAS ( RUSTICO )", "LAS FUENTES DE SAN PEDRO", "PORTAFONTANA", "VALLE DEL PALMAR",
    "SANTA ANITA", "VILLAS DE SAN JUAN 2 SECC.", "PASEOS DE SAN ANGEL",
    "ARBOLEDAS DE LA LUZ", "INDUSTRIAL GENESIS", "LOMAS DE LOS NARANJOS", "EL PORVENIR",
    "MEZQUITAL DEL CARMEN", "ALAMEDA DE LA PRESA", "LA VIRGEN", "RESIDENCIAL EL MEZQUITE",
    "LOS MURALES II", "PASEO DE LA CASTELLANA", "BOSQUES DE SAN ANDRES",
    "PORTON DE LOS GIRASOLES", "VILLA OLIMPICA", "BRISAS DEL LAGO I",
    "PRADERAS DE AGUA AZUL", "VILLAS DEL CARMEN", "RESIDENCIAL LAS FLORES",
    "PASEOS DEL BOSQUE", "VILLA CONTEMPORANEA", "JARDINES DE SANTA FE", "LA FRAGUA",
    "SANTA CATALINA", "PUERTAS DE LA ALBORADA", "CUMBRES DE LOS ALPES",
    "BOSQUE DE LOS NARANJOS", "COLINAS DE SAN FRANCISCO", "VILLAS DEL BAJIO",
    "BOSQUES DE LA PRADERA", "VILLA DEL LAGO", "RESIDENCIAL EL FARO", "VILLAS DEL ROCIO",
    "JARDINES DE LOMAS DE MEDINA", "VALLE DEL CONSUELO", "HABITACIONAL LOS CARCAMOS",
    "BRISAS DE SAN FRANCISCO", "VALLE DE LA LUZ", "SAN FRANCISCO(II SEC AMPLIACIO",
    "LOS COLORINES", "SINARQUISTA", "METROPOLI RESIDENCIAL", "FORANEOS", "REAL BUGAMBILIAS",
    "COLINAS DE SANTA JULIA II", "TODOS LOS SANTOS", "DESARROLLO DEL LAGO",
    "HACIENDA SAN MIGUEL", "VILLA LA RIOJA", "RESIDENCIAL NIZA", "HACIENDA BUGAMBILIAS",
    "HACIENDA DEL CARMEN II", "PRIVADA TABACHIN DEL VALLE", "PUERTA SAN RAFAEL",
    "TERRA COTTA", "INDUSTRIAL CAMPO VERDE", "VALLE DE SAN JAVIER", "AMPLIACION MEDINA OTE",
    "JARDINES DE LA BUFA", "SAN JUDAS (RANCHO)", "PASEO DE LA PRADERA",
    "LA NORIA DE SEPTIEM", "PASEO DEL COUNTRY", "CIMA DIAMANTE", "LA MORENA I(EX HACIENDA)",
    "MISION LA CAÑADA", "EL PALMAR", "VILLAS DE GUADALUPE", "PEDREGAL DEL CAMPESTRE",
    "PORTON DE BUGAMBILIAS", "COLINAS DEL CARMEN", "LA MURALLA", "LA CINTA", "RANCHO GRANDE",
    "SAUZ DE ARMENTA", "JALAPA", "EL TOMATE", "LINDERO VIEJO", "SAN ROQUE DE TORRES",
    "EL MAGUEY", "PUERTA DE SANTA RITA", "EL DESAGUE", "SAN JUDAS", "ESTANCIA LOS SAPOS",
    "EL RATON", "LOS PACHECOS", "ARROYO SECO", "SAN PEDRO DEL MONTE",
    "SAN ISIDRO LAS COLONIAS", "CAMPESTRE LOMA GRIEGA", "LOMA GRIEGA",
    "POBLADO DE LAGUNILLAS", "LAS COLORADAS", "EL BAJIO", "TORREMOLINOS",
    "CAMPESTRE LOS ENCINOS", "JARDINES DEL VALLE", "DUARTE", "LOS SAUCES", "SAN JUAN DE OTATES",
    "LOMAS DE COMANJILLA", "EL RELICARIO", "LLAGUNO A.C.",
    "FIDEICOMISO CIUDAD INDUSTRIAL", "CENTRO DE PREVENCION SOCIAL",
    "UNION COMUNITARIA LOS LAURELES", "VILLAS DE NTRA SRA DE LA LUZ 1",
    "POLIGONO INDUSTRIAL MILENIO", "VALLE ANTIGUA", "PASEOS DEL MOLINO",
    "HACIENDA SAN ANGEL", "EXHACIENDA LA MORENA (I/II)", "EL CONSUELO (VIII SEC.)",
    "FRUTAL DE LA HACIENDA I", "BRISAS DEL VERGEL", "LA CAPILLA DE ALFARO",
    "POZO DEL HABITACIONAL", "AZUL MAGUEY", "DESARROLLO EL POTRERO", "LOMAS DE LAS HILAMAS",
    "PEDREGAL SATELITE", "PARQUE INDUSTRIAL SAN CRISPIN", "MISION PROVIDENCIA",
    "PASEO DE LAS MORAS", "ENTRE DOS AGUAS", "FORESTA JARDIN", "QUINTA LOS NARANJOS",
    "ARBOLEDA SAN JOSE", "EL MIRADOR DE GRAN JARDIN", "NATURA RESIDENCIAL",
    "COUNTRY DEL LAGO I Y II", "LOMAS DEL REFUGIO", "CAMPO VIÑA", "PUERTA DE HIERRO",
    "REAL DE LAS PALMAS", "GRAN JARDIN", "VALLE DE LOS PINOS", "MISION DE LA PRESA",
    "MISION DEL CARMEN", "REAL DE VILLA", "COLINAS DE LA FRAGUA", "JUAN VALLE",
    "FRACCION DE ALFARO", "CUMBRES DEL SOL", "PARQUES DEL SUR IV", "BRISAS DEL PEDREGAL",
    "REAL DEL REFUGIO", "CORTIJOS DE LA GLORIA", "EL RECUERDO", "NUEVA SAN CARLOS",
    "RESIDENCIAL VERANDAS", "LA PIRAMIDE", "PARQUES DEL SUR V", "ANTURIOS(P.SN MIGUEL)",
    "LA CONDESA", "VILLAS DE SAN NICOLAS", "CAMPO DE GOLF DEL CAMPESTRE",
    "PRADERA DEL BOSQUE", "PEDREGAL DEL GIGANTE", "RINCONADA DE ECHEVESTE",
    "VILLAS JACARANDAS", "FRACCIONAMIENTO LAS CRUCES", "BRISAS DEL PEDREGAL 2",
    "VILLAS DEL MAYAB II", "DESARROLLO DEL LAGO SEC MARINA", "BARRANCA DEL REFUGIO",
    "JOYAS DE CASTILLA", "QUINTAS LA HUARACHA I II Y III", "HACIENDA SAN JOSE", "SAN ALFONSO",
    "PIAMONTE", "PLAZA MARINA", "LA CANTERA", "SAN NICOLAS DE LOS GONZALEZ", "CAMPO FUERTE",
    "VILLAS DE LA PRESA", "EL CAMPANARIO", "REAL LOS MURALES", "OASIS", "COLINAS DE PLATA",
    "RANCHO EL CAPRICHO", "BALCONES DE LA FRAGUA", "LA TOSCANA", "VALLE DE SAN PEDRO(JOYA I)",
    "JARDINES DE LOS NARANJOS", "VILLAS DE LAS PALMAS", "PUNTA CAÑADA",
    "ERMITA DE IBARRILLA", "CAMPO PALMYRA", "PORTALES DE SANTA URSULA", "EL SUSPIRO",
    "VALLE ESCONDIDO", "EL YACIMIENTO", "HACIENDA LOS OTATES", "CUMBRES DE LA GLORIA",
    "SAN JOSE DE LOS MONTES", "SANTA ANA, A.C.", "LOZA DE LOS PADRES",
    "PASEOS DE LAS TORRES", "BALCONES DE LA PRESA", "BOSQUE AZUL", "OBSERVATORIO II",
    "COUNTRY CLUB GRAN JARDIN", "LOS VALTIERRA", "JARDINES DE SAN JUAN", "CAÑADA DEL REAL",
    "PLATINO", "VILLAS DE NTRA SRA D LA LUZ 3", "PASEOS DE LA PISCINA", "VISTA ESMERALDA II",
    "MI ESPERANZA", "COYOACAN", "SAN ISIDRO DE LAS COLONIAS", "EL ROTARIO",
    "PASEOS DE ANDALUCIA", "DESARROLLO MIXTO LAS VESTALES", "PASEOS DE LA FRAGUA",
    "GRAN BAHIA", "PUNTA DEL ESTE", "BALCONES DEL CAMPESTRE 3RA SEC", "MONTAÑAS DEL SOL",
    "HUERTAS DE MEDINA I", "EL MOLINO", "JARDINES DE LA PRESA", "RINCONADA DE LA PRESA",
    "PUNTA DEL SOL", "EL PARAISO LOS ARCOS", "QUINTAS DEL SOL", "LAS MAGNOLIAS",
    "NUEVO PROGRESO", "FRUTAL DE LA HACIENDA II", "LOMAS DE IBARRILLA", "PRESA DE LA JOYA",
    "PRADERAS DEL REFUGIO", "CERRO GORDO", "C.H. CAMPO VERDE", "PARQUES DE SAN JUAN",
    "PRIVANZA LOS NARANJOS(I Y II)", "PORTON CAÑADA", "BENEVENTO",
    "COND. HABITACIONAL VESTALES", "COND. HABITACIONAL HESTEA", "COND. HABITACIONAL HERA",
    "PRO SUR HACIENDA SAN MIGUEL", "EL SAUCILLO", "SAN JOSE DE LA JOYA(EJIDO)",
    "PORTA TOSCANA", "EL ALAMO", "HACIENDA LOS MORALES", "JARDINES DE ANDALUCIA",
    "CAMINO A SAN JUAN", "BALCONES DE LA PRESA II", "LUZ DEL PARQUE", "JARDINES DE LOS REYES",
    "CUMBRES DE LA PRADERA", "VILLA SUR", "AMP. JARDINES DE MARAVILLAS",
    "RIBERA SAN BERNARDO", "PIEDRA AZUL I", "PIEDRA AZUL II", "VILLA CONSTELACIONES",
    "JOYAS DE CASTILLA PLUS", "SAN ANTONIO DEL MONTE(MALAGANA)", "LA MORA", "EL NACIMIENTO",
    "LA RESERVA", "PUERTA DE SAN GERMAN", "EL RAMILLETE", "ESTANCIA DE VAQUEROS",
    "LA CORREA", "COMUNIDAD DEL CONSUELO", "SAN J. RESPLANDOR(EL CAPRICHO)",
    "EL TOPE DE LA SANDIA", "RANCHOS", "CAÑADA DEL CAMPESTRE", "PASEOS DE LOS PIRULES",
    "LA MARQUESA", "ALTAVISTA", "URBIVILLA DEL ROBLE", "CASA DE PIEDRA", "DANUBIO AZUL",
    "VILLA DE CIRELLA", "BRISAS DEL PEDREGAL 5", "FRACCIONES CAÑADA DE ALFARO",
    "NUEVA ERMITA", "HORIZONTE AZUL", "POLIGONO INDUSTRIAL JEREZ", "ALAMEDAS DE ESPAÑA",
    "CLUB LOYOLA", "HACIENDA DE IBARRILLA", "RIVERA DEL CARMEN", "SANTA CRUZ",
    "VALLE DE LAS TORONJAS", "VALLE DEL CARMEN", "RINCON DE LA ESMERALDA", "EL RUBI",
    "PASEOS DEL ARROYO", "CAÑADA DIAMANTE", "PINAR DEL TAJO", "LA NOPALERA",
    "SAN JUAN BOSCO III", "CERRITO DE LA JOYA", "HUERTAS DE MEDINA II", "LAS JOSEFINAS",
    "LUCERO DE SAN NICOLAS", "LOS HEROES LEON", "VILLAS DE SAN NICOLAS III", "EL DORADO",
    "AMPLIACION LATINO", "MAR SOL II", "LOMAS DE CONTRERAS", "COMUNIDAD PIEDRA BLANCA",
    "LA PERLITA", "CUESTAS DEL ROCIO", "BRISAS DEL PEDREGAL 6", "FUENTES DEL VALLE",
    "AMPLIACION JARDIN DELTA", "ESPERANZA DE ALFARO", "GRAN PARAISO", "SIGLO XXI",
    "LOS PINITOS", "LA FORESTA RESIDENCIAL", "ORIENTE MIRAVALLE", "LA VIGATTA",
    "LAS MANSIONES", "VILLA REAL", "ARBOLEDAS DE LA SELVA", "VILLAS DE SAN NICOLAS III NTE.",
    "REAL 2000", "LOMAS DE LA SELVA", "SAN JUAN", "HACIENDA DE SAN NICOLAS",
    "PARQUE DEL CASTILLO", "SANTA MAGDALENA", "VILLAS DEL CAMPO", "EL PEDREGAL",
    "HACIENDA DE IBARRILLA II", "PRADERAS DEL SOL", "TAJO DE LA PRESA", "PUERTA SAN CARLOS",
    "PUERTA DORADA", "LUZ DE LA PRESA", "FRACCIONES DE LOS ARCOS", "CRUZ DE LA SOLEDAD",
    "RIBERA DE LA JOYA", "CERRITO AMARLLO I", "CERRITO DE LA JOYA II", "BRISAS DEL SOL",
    "HACIENDAS DE GUADALUPE", "PUENTE DEL ANGEL", "SAN JUAN BAUTISTA", "LA JALISCO",
    "NOPALERA", "CIUDAD INDUSTRIAL III ETAPA", "PORTAL LA LUZ", "SIERRA NOGAL",
    "BRISAS DEL CAMPESTRE", "FRACCIONES DE SAN JUAN BAUTIST", "VILLAS DEL MAGUEY",
    "MAR SOL I", "PREDIO EL CRESPO", "SANTA JULIA DE JEREZ", "RIBERA DE SAN BERNARDO",
    "VALLE DE LOS MILAGROS", "TORRES DE LA JOYA", "MISION DE LA JOYA", "VILLAS DEL PEDREGAL",
    "INDUSTRIAL LAS CRUCES", "INDUSTRIAL BRISAS DEL CAMPO", "LAURELES VALLARTA",
    "RESIDENCIAL DEL PARQUE", "MEGA PRICE", "EL TLACUACHE NORTE", "JARDIN ALAMEDA DIAMANTE",
    "EL GRANJENO SUR", "EL TLACUACHE SUR", "PRIVADA GAMIÑO", "PRIVADA DEL CAUDILLO",
    "HACIENDA SANTA CATALINA", "SAN PEDRO DE LOS HDEZ. NTE.", "SAN CAYETANO DE MEDINA",
    "PASEO DE MARAVILLAS", "TORRES DEL SOL", "FRACCION SN.CAYETANO DE MEDINA", "TECNOLOGICO",
    "CAYETANA RESIDENCIAL", "QUINTA HILARIO MEDINA", "DEL POZO", "SAN ISIDRO II",
    "RESIDENCIAL SAN ISIDRO II", "RESIDENCIAL SAN ISIDRO III", "LA HACIENDITA",
    "DEPORTIVO FLEXI", "TORRES PREMIER", "EL ARBOL", "PRO SUR LOS NARANJOS",
    "SUR SANTA ROSA DE LIMA", "INDUSTRIAL SANTA JULIA", "PREDIO SAN JOSE EL ALTO",
    "NUEVO MILENIO", "PRO.SAN MIGUEL DE RENTERIA", "CRUZ DE LAS HILAMAS",
    "PORTONES DE SAN JACINTO", "PUERTA HORIZONTE", "VILLAS LA GLORIA", "GRANJA LOS PORTALES",
    "CERRITO DE JEREZ NORTE", "VALLE DE SAN PEDRO(JOYA II)", "VALLE DE SAN PEDRO LA JOYA III",
    "VALLE DE LAS TORRES PTE.", "VALLE DE LAS TORRES OTE.", "BRISAS DEL LAGO II",
    "PLAZA HIDALGO", "FRACCIONES DEL CRESPO", "CONJ.HAB.JAIME NUNO",
    "PRO SAN PEDRO DE LOS HDEZ. NTE", "PRIV.CONCEPCION(BARRIO DE GPE)",
    "DEPORTIVA ENRIQUE FERNANDEZ M.", "RINCON DE BUGAMBILIAS", "LOS TEPETATES",
    "REAL DEL CASTILLO II", "VISTAERO", "SAN JORGE LOS CASTILLOS", "MESITAS DEL CONSUELO",
    "RESIDENCIAL SANTA FE", "LA PIEDRERA", "CERRITO DE LAS FLORES", "SAN PABLO II",
    "PRO FRACCIONES DE ECHEVESTE", "PRO.NTE. SAN BERNARDO", "BOSQUES DEL CARMEN",
    "VILLAS DE GUANAJUATO", "LOMA DE LA PAZ", "COLINA REAL DE LA JOYA", "LAGOS DE MEDINA",
    "CLUB HIPICO", "LOMAS DE LA HACIENDA", "BRISAS DE ECHEVESTE",
    "PREDIO RUSTICO LOS ANGELES", "PUERTA DEL SOL", "FRACCIONES SAN PEDRO",
    "PRO SUR SAN PABLO", "PORTONES DE GRAN JARDIN", "SAN NICOLAS DEL PALOTE NTE.",
    "SAN BERNARDITO", "EL RANCHITO", "VALLE DEL CONSUELO II", "ESCONDIDA DE LA SELVA",
    "EL VIVERO", "PRO FRACCIONES DE IBARRILLA", "PRO PTE SAN PABLO", "PRO NTE LA NORIA",
    "PRO EL CASTILLO NTE", "PRO CAÑON DE LA INDIA NTE", "RINCON DE LOS NARANJOS",
    "VILLAS LA LUZ", "VILLAS DE BARCELO", "CAMPOS DE FUT BOL HIDALGO", "AMPLIACION MEDINA II",
    "PASEOS DE LA FRAGUA II", "RINCON DE ASIS", "BODEGA AURRERA", "PARQUE CHAPULTEPEC",
    "FRACCIONES DE SAN NICOLAS", "PRO NTE. STA.MARIA DE CEMENTOS", "JARDINES DE SAN MIGUELITO",
    "PRIVANZA DEL CONDADO", "LA MEDALLA", "SAN ISIDRO AZTECA", "IBARRILLA", "PRESA ECHEVESTE",
    "LA PERA", "PRO ARBOLEDAS DE LA LUZ SUR", "SAN ANTONIO DEL ALAMBRADO", "LAS TROJES III",
    "CONJUNTO HABITACIONAL VICENTE", "CENTRO BODEGUERO LAS TROJES", "PREDIO CERRITO DE JEREZ",
    "SOBERNA", "ZOOLOGICO", "AMPLIACION EL CARMEN", "VILLAS DEL COUNTRY",
    "PANTEON SAN SEBASTIAN", "POLIFORUM", "EXPLORA", "ARCOIRIS", "LOS LAURELES II", "KILLIAN",
    "EL TECOTAN", "PRIVADA ECHEVESTE", "PRO PTE HACIENDA ECHEVESTE", "PRO OTE SANTA CECILIA",
    "VALLE HERMOSO", "PRO RUSTICO LA NORTEÑA", "GRANJA STOEVER", "PASEOS DE LA PRESA",
    "PRO PTE VALLE DE LOS CASTILLOS", "TIRITAS III", "TIRITAS IV", "LA LADERA", "LOS CASTORES",
    "EL MAYORAZGO", "PRIVADA DEL ROBLE", "PRO SUR VALLE DEL MORAL",
    "PRO PREDIOS HISPANOAMERICANO", "C.H. MARFIL", "PRO NTE VALLE HERMOSO",
    "PRO FRACCIONES DEL PALOTE", "LOMA DORADA", "AMAZONAS", "RESIDENCIAL TITANIO",
    "LAS CUPULAS", "CENTRO COMERCIAL LOS PARAISOS", "LA QUERENCIA", "BOSQUES DEL PEDREGAL",
    "ARCOS ANTIQUA", "PRIVADAS DEL REAL", "FRACCION DEL GRANJENO", "VILLAFRANCA",
    "CONJUNTO HAB. LAURELES", "CONJUNTO HAB. CEDROS", "CONJUNTO HAB. TULIAS",
    "FRUTAL DE LA HACIENDA III", "TABLAS DE LA VIRGEN", "SANTA LUCIA", "SUB ESTACION NTE CFE",
    "BALCONES DE LA PRESA III", "FORD DEL CAMPESTRE", "INDUSTRIAL HIDALGO", "LOS NOGALES",
    "PRESA EL PALOTE", "PRO GRANJAS STOVER", "SAN NICOLAS DEL PALOTE",
    "FRACCION DE LOS GOMEZ SUR", "HACIENDA DEL CARMEN", "PREDIO RUSTICO LA NORTEÑA",
    "CENTRO COMERCIAL INSURGENTES", "PRO PTE VALLE DE LOS CASTILLOS", "TRES CANTOS",
    "PORTONES DEL BOSQUE", "PUERTA SIGLO XXI", "GLADIOLAS", "PUNTA NOGAL LA LUZ", "JALISCO",
    "PRIVADA ALBORADA", "VALLE DIAMANTE", "KATANIA", "VALLE DE OTATES", "REAL DE SAN ANTONIO",
    "ESTANCIA DE LA JOYA", "VALLES DE MEXICO", "HACIENDA DE IBARRILLA I",
    "GRANJAS SANTA CRUZ", "ALAMEDAS DE ALCAZAR", "SAN JOSE DEL POTRERO",
    "RINCON DE LA JOYA", "PUNTA NOGAL MORELOS", "PREDIO RUSTICO EL RATON", "AMBERES",
    "PORTON DEL VALLE", "PRADOS LA LUZ", "PRIVADA ROSALES",
    "CONJUNTO HABITACIONAL RIO MAYO", "PASEOS DE MARAVILLAS III", "BOSQUES DE LA SELVA",
    "CASTILLO DE SAN GABRIEL I", "EL PENITENTE 2 SECC.", "DESARROLLO DEL LAGO",
    "LOMA DE CONTRERAS", "PREDIO POTRERO DE LAS CEJAS", "LORETO", "LA LOMA", "LA YESCA",
    "EDIFICIO CIMA", "LA CIMA DE LEON", "CONGREGACION DE LOS CASTILLOS", "EL CLAVEL",
    "CANTARRANAS", "BAUTISTA (SAN JUAN DE ABAJO)", "PRIVADA DEL CARMEN",
    "SN FCO (SAN JOSE DE LOS DURAN)", "LA TINAJA", "LA PROVIDENCIA", "ALBAZUL",
    "THOMAS JEFFERSON", "TORRES DE LEON", "TORRES DEL PARQUE", "ZANDA", "TORRE AZUL",
    "RANCHO LOS NARANJOS", "LA PATIÑA", "VILLAS DE PALERMO", "CIBELES", "PUERTA DE SAN CARLOS II",
    "PREDIO CERRO GORDO", "PASEO DE LOS NARANJOS", "PREDIO RUSTICO EL ROSARIO", "EL TUCAN",
    "PARQUE IND. COLINAS DE LEON", "CORDILLERA RESIDENCIAL", "BOSQUES DE SAN JUAN",
    "CONJ.HAB. CENTENARIO", "MINERAL DE LA JOYA", "LAS SENDAS", "SAN JOSE DEL SAUCILLO",
    "SANTA CRUZ III", "EL CASERIO", "CUMBRES DE MEDINA II", "PEDREGALES DEL SOL",
    "LOMAS DEL SOL III", "EL PARAISO LOS LOPEZ", "LOMAS DE LA PAZ", "PARAISO DIAMANTE",
    "SAN JUAN DE ABAJO ORIENTE", "SAN JUAN DE ABAJO ORIENTE SUR", "PREDIO SAN CARLOS",
    "DIOSAS DEL HOGAR", "ALAMEDAS DE VILLAFRANCA", "RAMIREZ GARCIA", "LOMAS DEL CERRITO",
    "ARTICULO CUARTO CONSTITUCIONAL", "CEMENTOS", "EL CIELO", "TORRES DEL SUR",
    "VALLE DE LAS AVES", "TRENTO", "VILLAS ALTARIA", "CASTELLO", "RIBERA DE BARCELO",
    "SANTA CRUZ II", "LAS TORONJAS", "CERRITO DE GUADALUPE", "LOMAS DEL EDEN",
    "JARDINES DEL RIO", "FANEGA DE LA NOPALERA", "LOMA VERDE III", "RESIDENCIAL ESMERALDA",
    "RESIDENCIAL RUBI", "EL LAUREL", "SAN CARLOS LA RONCHA", "VALLE DE LA JOYA", "IBARRILLA",
    "LOS LOPEZ", "TORRES DE LA PRESA", "LA LOZA DE LOS PADRES", "VALLE DEL GIGANTE",
    "PRIVADA VILLA DE LOS NARANJOS", "SAN PEDRO DEL MONTE", "VYNMSA LEON INDUSTRIAL PARK",
    "SAN BENITO ABAD", "CUMBRES DE LAS HILAMAS", "NAICA", "VALLE DEL ROBLE", "TORRES DORADAS",
    "LOMAS PUNTA DEL ESTE", "LAGUNILLAS", "LOS CASTILLOS", "TORRES DE SAN NICOLAS",
    "MONTOLIVO", "OJO DE AGUA DE LOS REYES", "OJO DE AGUA DE LOS REYES",
    "PIEDRA AZUL DEL BAJIO", "RESIDENCIAL ZAFIRO", "HACIENDA DE VALBUENA", "BOSQUE SAN CARLOS",
    "BALCONES DE LEON", "TORRES MAYORAZGO", "TORRE CAÑADA", "PUNTA DORADA",
    "PRIV. MISION SAN AGUSTIN", "LA JOYA", "VILLAS DE SAN JACINTO", "VALLE AZUL",
    "TABACHINES", "ALDABA", "LADRILLERAS DEL REFUGIO", "MAYORCA", "FLOR DEL VALLE",
    "VILLAS DE LA JOYA", "MIRADOR DE LOS CASTILLOS", "RIVERA DE LA JOYA",
    "PRADOS DE SAN NICOLAS", "RIVERA DEL CARMEN II", "LUZ DEL REFUGIO", "AZAHARES",
    "PARQUE INDUSTRIAL LEON BAJIO", "TORRE TAWA", "ALAMEDAS DE BARCELO",
    "ARBOLEDAS DEL CAMPO CAMPESTRE", "VIBAR II", "VILLAS DEL BOSQUE", "JARDINES DE VERSALLES",
    "RESIDENCIAL CARMENA", "SAN JERONIMO II SEC.", "LOMBARDIA", "PREDIO EL PALOTE",
    "JUAN XXIII", "SAN JOAQUIN", "SAN JUAN DE ABAJO CENTRO", "CAÑADA REAL DE MARICHES",
    "AIREN", "ARANCIA", "MEDINA", "LAS HILAMAS", "BOSQUES DEL SUR II", "TORRES NYMPHE",
    "MULTIFAMILIAR GRANADA", "PORTA ROMANI", "LOS MEZQUITES", "LAS VIOLETAS", "EJIDO DE SILVA",
    "LOS AGAVES", "MARBELLA", "DEPORTIVA II", "MALAGANA", "BOSQUES DE MEDINA", "LOS GOMEZ",
    "CAPELLANIA", "PREDIO SANTA FE", "HACIENDA DE LEON", "LOS AGUACATES", "RIO GRANDE",
    "PASEO DE LOS LAURELES", "VALLE DE LAS FLORES", "SAN ISIDRO DE JEREZ II",
    "HACIENDA DE LAS TROJES", "PREDIO ECHEVESTE", "ALALBA", "CAMINO A SAN JUAN II",
    "LOMAS DE SAN JOSE DE LA JOYA", "PRO NORTLA NORIA", "ZARCHUILES", "ANISA",
    "PRIVADA ROSALES", "CIUDAD SATELITE", "PRIVADA CONCEPCION", "PREDIO EL SACRAMENTO",
    "VILLAS DE SAN NICOLAS II", "RANCHO VIEJO", "MA. PAZ", "LA CAÑADA", "VILLAS DE SAN JUAN I",
    "SAN JOSE DEL DURAN II", "PILETAS I Y II", "CAÑADA DE LOS NARANJOS",
    "LOMAS DE VISTA HERMOSA II", "CAMPOS ELISEOS", "LA SAUCEDA", "PREDIO RACHO SECO", "CANAH",
    "CONJUNTO HABITACIONAL ROCIN", "SACROMONTE", "SAN JUAN BOSCO", "SAN NICOLAS DE URTEAGA",
    "PARAISO DE LAS JOYAS", "PEDRALTA", "CANDORA", "LA ALAMEDA", "SAN JOSE",
    "JARDINES DE JEREZ", "RIZOS DEL SAUCILLO", "LOMAS DE SAN FRANCISCO", "CHALET LA CUMBRE",
    "ABEDUL", "GUADALUPE", "TORRES ALFA", "HACIENDAS SAN NICOLAS", "SAN JOSE DEL REFUGIO",
    "ARRAS RESIDENCIAL", "EL TREBOL", "VILLAS DEL MAYAB I", "EJIDO SAN CARLOS",
    "LOMAS DE VISTA HERMOSA SUR", "COND. HABITACIONAL CUMBRES",
    "CONJUNTO HAB.VILLAS DEL BOSQUE", "SAN MIGUEL DEL PALOTE", "TAJO", "LAS TIRITAS",
    "LAS MANDARINAS", "SAN FRANCISCO", "CAMPESTRE EL REFUGIO", "ARIA", "REAL DEL MEZQUITE I",
    "BOSQUES LATINOAMERICANOS", "LA VALENCIANA", "MARROKA", "PARQUE SUR LEON EL SAUCILLO",
    "CAMPESTRE SANTA CRUZ", "CELTA DE VIGO", "LA ORDEÑA", "BINEN", "EL SAUZALITO",
    "PRO NORTE LAS JOYAS", "RINCONADA DE IBARRILLA", "ANZURES", "CABO METROPOLITANO",
    "LA ENCANTADA", "PEDERNALES Y ZENDEJAS", "HAUS LEON", "PUNTA NATIVA", "TORRE MITRA",
    "EJIDO DE POMPA", "VILLAS DE SAN JUAN 2.0", "RIVERA DE MEDINA", "VILLA UNIVERSIDAD",
    "HACIENDA DE ALBA", "GRANJAS MARIA DOLORES", "VALLE DE LAS FLORES.VALLEVERDE",
    "COLINAS DEL RECUERDO", "CAPITTALA", "TORRENTO", "COMUNIDAD EL TREBOL", "EL PUEBLITO",
    "ESMERALDA DEL BAJIO", "C.H. COLINAS DE SAN ISIDRO", "MURANO", "RANCHO SECO",
    "VISTA HERMOSA", "FRACCIONES DEL GUAJE", "PRIVADA HISTORIADORES", "PRO OTE PEMEX",
    "MISIONES DE SANTA FE", "SENDEROS", "PARQUE IND. SANTA MONICA", "BUENAVENTURA",
    "TORRES LEON", "POTRERO DE LA CAJA", "PRO FRACC DE PURISIMA DE JEREZ", "PROVINCIA CASTELL",
    "LOMA DE LAUREL", "PORTALES DE MIRAVALLE.ANTILLAS", "LYRATA", "GUADALUPE VICTORIA",
    "LUCERNA", "ROBLE DE SAN PABLO", "RUBI DEL BAJIO", "LOMAS PUNTA DEL ESTE IV",
    "TORRE BASANIA", "TORRES MIRADOR", "POLIGONO IND. BICENTENARIO", "TORRE KENZO",
    "PANORAMICO I", "INTERLOMAS", "CATALUÑA", "CARTAGENA", "NUEVO SAN FRANCISCO",
    "EL VALLADITO", "CONJUNTO HABITACIONAL LEON I", "LUGANO RESIDENCIAL", "LOS ANGELES II",
    "VILLAS DE NTRA SRA DE LUZ II", "PUERTA DE SAN CARLOS 1", "EL FARO", "MONTAÑA DEL SOL",
    "SANTA CECILIA III", "PARQUE PRIMAVERA", "INDUSTRIAL LA POMPA", "ZAFIRO DEL BAJIO",
    "JOYAS DE CASTILLA PLUS I", "GRANJAS SAN CARLOS", "WEST TOWERS", "JOHN F. KENNEDY",
    "PREDIO EL GUAJE", "PASEOS DE MIRAVALLE III", "PUNTA MAYOR", "LOMAS DE SANTA ISABEL III",
    "SANGRE DE CRISTO", "RIO MAYO", "CAMELINAS", "JOYAS DE CASTILLA PLUS III/IV",
    "GRANJENO PLUS IVEG", "VILLAS DE BARCELO III", "EL DORADO II", "VILLA SUR I",
    "HERNANDEZ-ROUGON", "INDUSTRIAL ARCO SUR", "LOMAS DEL SOL I", "VILLA MADERO",
    "LOMAS DE CONTRERAS II", "PRO NTE REFUGIO DE SAN JOSE", "BOSQUES DE BREDA",
    "LOMAS DEL PEDREGAL", "PARQUE IND. COLINAS DE LEON II", "PUNTA MIXE",
    "CUMBRES DE LA GLORIA IV", "PTE.IBARRILLA", "HACIENDA SANTA FE",
    "PRO VIVIENDA OBRERA EL SALTO", "VALLE DE SAN FRANCISCO", "VALLE DE SAN CARLOS I",
    "CUMBRES", "MURANO II", "CASTELLO II", "SAN JUAN DE ABAJO PTE", "DIVINA PROVIDENCIA",
    "RAMIREZ GARCIA (LA MERCED)", "FATIMA", "VALLE DEL REAL II", "JOYAS DE CASTILLA PLUS II",
    "RIVERA DEL RIO", "PRIVANZZA VILLAFRANCA", "LOMAS DE LA CAÑADA I", "VALLE IMPERIAL I",
    "LOMAS DE LA CAÑADA II", "SANTA GERTRUDIS", "LAS VESTALES PLUS", "IMPERIO AZTECA",
    "CALAFIA", "LOMAS DEL ASTILLERO", "CENTRO GASTRONOMICO LA CIMA",
    "SN NICOLAS DE PALOTE PRADERA B", "PRO FRACCIONES DE EL ALTO", "REAL MEZQUITE II",
    "GRANJA SANTA TERESA", "ALBAZUL II", "CONDOMINIO OLIVIAS", "LA ESPAÑOLA", "DE LOS ROSALES",
    "VARAL DE LOS CASTILLOS", "COMPLEJO BARRANCA DE VENADEROS", "VALLE NUEVO DEL CONSUELO",
    "VALLE IMPERIAL II", "TORRE LAR", "LA VIGATTA 2", "LAS FLORES", "VILLAS SANTA TERESITA",
    "FRACCIONES DE SANTA JULIA", "MANDUJANO (P LOS PIRULES)", "ARBOLEDAS DE SAN HILARION",
    "TIERRA SANTA II", "NIZA", "LA HERMITA I", "PREDIO RANCHO BELLA VISTA", "PUERTA LISBOA",
    "HACIENDAS DE SAN CARLOS", "LA HERMITA II", "RESIDENCIAL SAN PEDRO", "HACIENDA VIÑEDOS II",
    "PORTA VEDRA", "LAS VIZCAINAS", "ARZUA", "TRACIA", "PREDIO LOS NARANJOS",
    "BRISAS DEL LAGO 2", "AMPLIACION SAN FRANCISCO II", "PARQUE IND.METROPOLITANO BAJIO",
    "LUSANTA", "EL LUCERO IV", "TIERRA SANTA I", "FRACCION DE JOCONOXTLE",
    "PARQUE IND. ECOLOGICO DE LEON", "ALAMEDAS", "LA MOREÑA II", "BRISAS DE SAN FRANCISCO II",
    "PARQUE INDUSTRIAL VAZ", "TORRE NIMBUS", "FRACCIONES DE SANTA LUCIA", "AGUA AZUL II",
    "EL PARAISO", "TORRE CAMPESTRE", "VALLE DE LA LUZ II", "COLINAS DE LA FRAGUA PLUS",
    "JUAN CAPISTRANO", "LOS ARRAYANES II", "SUB ESTACION NORTE", "PRO SUB ESTACION NORTE",
    "TORRE HERANA", "LOMA DORADA I", "LA SOLEDAD", "MONTE DE CRISTO", "PRIVANZA BOUTIQUE",
    "CASCO SAN CARLOS SECC.EL BURRO", "PUERTA DE SAN CARLOS 1", "ZERENA RESIDENCIAL",
    "VILLAS DE SAN NICOLAS I", "AMP. VALLE DE SAN BERNARDO", "POPULAR INCA",
    "SUR SAN JOSE DEL CONSUELO", "PINARES", "LA ASTURIANA", "CAMINO REAL DE LA JOYA",
    "ALTA SIERRA", "FLORES MAGON", "VALLE DE LAS HACIENDAS", "ALMAZARA", "ARONA",
    "PUNTA DEL ESTE II-III-IV-V-VI", "VALLE DE LAS TORRES II", "ARBOLEDAS DE SEÑORA",
    "EL GRANJENO PLUS", "BOSQUES DE SAN JUAN II"
];

// Agregar macros (puedes personalizar esta lista según tus necesidades)
export const MACROS = [
    "Macro 1", "Macro 2", "Macro 3", "Macro 4", "Macro 5", 
    "Macro 6", "Macro 7", "Macro 8", "Macro 9", "Macro 10"
];

export function cargarColoniasMacros() {
    const select = document.getElementById('filtroColoniaMacro');
    if (!select) return;

    // Limpiar opciones existentes (excepto la primera)
    while (select.options.length > 1) {
        select.remove(1);
    }

    // Agregar colonias
    COLONIAS_MACROS.forEach(colonia => {
        const option = document.createElement('option');
        option.value = colonia;
        option.textContent = colonia;
        select.appendChild(option);
    });

    // Agregar separador
    const separator = document.createElement('option');
    separator.disabled = true;
    separator.textContent = '──────────';
    select.appendChild(separator);

    // Agregar macros
    MACROS.forEach(macro => {
        const option = document.createElement('option');
        option.value = macro;
        option.textContent = macro;
        select.appendChild(option);
    });

    // Agregar funcionalidad de búsqueda
    agregarFuncionalidadBusqueda();
}

function agregarFuncionalidadBusqueda() {
    const select = document.getElementById('filtroColoniaMacro');
    if (!select) return;

    // Crear contenedor para el input de búsqueda
    const searchContainer = document.createElement('div');
    searchContainer.className = 'dropdown-search-container';
    searchContainer.style.position = 'relative';
    searchContainer.style.marginBottom = '5px';

    // Crear input de búsqueda
    const searchInput = document.createElement('input');
    searchInput.type = 'text';
    searchInput.placeholder = 'Buscar colonia o macro...';
    searchInput.className = 'form-control';
    searchInput.style.fontSize = '11px';
    searchInput.style.padding = '4px 8px';
    searchInput.style.height = '28px';
    searchInput.style.background = 'linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 100%)';
    searchInput.style.color = '#E0E0E0';
    searchInput.style.border = '1px solid #C1121F';
    searchInput.style.borderRadius = '4px';

    // Insertar el input de búsqueda antes del select
    select.parentNode.insertBefore(searchContainer, select);
    searchContainer.appendChild(searchInput);

    // Función para filtrar opciones
    function filtrarOpciones(termino) {
        const opciones = select.options;
        for (let i = 1; i < opciones.length; i++) {
            const opcion = opciones[i];
            const texto = opcion.textContent.toLowerCase();
            const coincide = texto.includes(termino.toLowerCase());
            
            if (opcion.disabled) {
                // Mostrar separadores solo si hay opciones visibles antes o después
                const opcionesVisiblesAntes = Array.from(opciones)
                    .slice(1, i)
                    .some((op, idx) => !op.disabled && op.style.display !== 'none');
                const opcionesVisiblesDespues = Array.from(opciones)
                    .slice(i + 1)
                    .some((op, idx) => !op.disabled && op.style.display !== 'none');
                
                opcion.style.display = (opcionesVisiblesAntes && opcionesVisiblesDespues) ? '' : 'none';
            } else {
                opcion.style.display = coincide ? '' : 'none';
            }
        }
    }

    // Event listener para el input de búsqueda
    searchInput.addEventListener('input', function(e) {
        filtrarOpciones(e.target.value);
        
        // Mostrar el dropdown si hay texto de búsqueda
        if (e.target.value) {
            select.size = 10; // Mostrar más opciones
            select.style.display = 'block';
        } else {
            select.size = 1;
            select.style.display = 'none';
        }
    });

    // Event listener para cuando el select pierde el foco
    select.addEventListener('blur', function() {
        setTimeout(() => {
            select.size = 1;
            select.style.display = 'none';
            searchInput.value = '';
            filtrarOpciones('');
        }, 200);
    });

    // Event listener para cuando el select recibe foco
    select.addEventListener('focus', function() {
        select.size = 10;
        select.style.display = 'block';
    });

    // Event listener para seleccionar una opción
    select.addEventListener('change', function() {
        if (select.value) {
            select.size = 1;
            select.style.display = 'none';
            searchInput.value = '';
            filtrarOpciones('');
        }
    });

    // Ocultar el dropdown inicialmente
    select.size = 1;
    select.style.display = 'none';
}

// Función para obtener la lista filtrada basada en un término de búsqueda
export function obtenerColoniasMacrosFiltradas(termino) {
    if (!termino) {
        return [...COLONIAS_MACROS, ...MACROS];
    }
    
    const terminoLower = termino.toLowerCase();
    const coloniasFiltradas = COLONIAS_MACROS.filter(colonia => 
        colonia.toLowerCase().includes(terminoLower)
    );
    const macrosFiltradas = MACROS.filter(macro => 
        macro.toLowerCase().includes(terminoLower)
    );
    
    return [...coloniasFiltradas, ...macrosFiltradas];
}